export const Icons = {
	star: "star",
	hotel: "hotel",
	location: "location-sharp",
	euro: "euro",
	search: "search",
	options: "options",
	sad: "sad",
	close: "close-a",
	chevronRight: "chevron-right",
	filter: "filter",
	list: "list-2",
	angleLeft: "angle-left",
	mapMarker: "map-marker-alt",
	clock: "clock",
	email: "email",
	phone: "phone",
	headphone: "headphone",
	picture: "picture",
} as const;
